# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
