# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-23 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expiration_date',
        ),
    ]
