# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-11 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20170311_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact_name',
            new_name='name',
        ),
    ]
